flaskforum/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError





class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Post Content', validators=[DataRequired()])
    submit = SubmitField('Post')

#
# class UpdatePostForm(FlaskForm):
#     title = StringField('Title', validators=[DataRequired()])
#     content = TextAreaField('Post Content', validators=[DataRequired()])
#     submit = SubmitField('Update')

flaskforum/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from ..models import User
from flask_login import current_user





class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=4, max=16)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('This username already taken')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email already taken')


class LoginForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=4, max=16)])
    password = PasswordField('Password',
                             validators=[DataRequired()])
    submit = SubmitField('Login')
    remember = BooleanField('Remember Me')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=4, max=16)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Update Pic',
                     validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('This username already taken')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('This email already taken')





class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('No Account with that Email')


class ChangePasswordForm(FlaskForm):
    password = PasswordField('New Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Request Password Reset')


class ChangePasswordManuallyForm(FlaskForm):
    password = PasswordField('New Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Request Password Reset')

flaskforum/main/routes.py
from flask import Blueprint

from flask import render_template, url_for, flash, redirect, request, abort
from ..models import User, Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home/")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=10, page=page)
    return render_template('main/home.html', posts=posts)


@main.route("/about/")
def about():
    return render_template('main/about.html', title='About')

flaskforum/posts/routes.py
from flask import Blueprint

from flask import render_template, url_for, flash, redirect, request, abort
from .forms import PostForm
#  UpdatePostForm?
from .. import db, bcrypt, mail
from ..models import User, Post
from flask_login import login_user, current_user, logout_user, login_required

posts = Blueprint('posts', __name__)




@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post1 = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        db.session.add(post1)
        db.session.commit()
        flash('Post has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('main/post_create.html', title='New post', form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('main/post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.id != Post.query.get_or_404(post_id).author.id:
        flash("It's not your post", 'danger')
        return redirect(url_for('posts.post', post_id=post_id))
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post info updated', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('main/updatepost.html', title=f'Update Post - {post.title}', post=post, form=form, legend=f'Update Post - {post.title}')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.id != Post.query.get_or_404(post_id).author.id:
        flash("It's not your post", 'danger')
        return redirect(url_for('posts.post', post_id=post_id))
    form = PostForm()
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted', 'success')
    return redirect(url_for('main.home'))

flaskforum/users/routes.py
from flask import Blueprint

from flask import render_template, url_for, flash, redirect, request, abort
from .forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ChangePasswordForm, ChangePasswordManuallyForm
from .. import db, bcrypt, mail
from ..models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from .utils import save_picture, send_reset_email

users = Blueprint('users', __name__)




@users.route('/register/', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user1 = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user1)
        db.session.commit()
        flash('Account created. You can sign in now.', 'success')
        return redirect(url_for('users.login'))

    return render_template('main/register.html', title='Register', form=form)


@users.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Successfully Logged in {form.username.data}', 'success')
            return redirect(url_for('main.home'))
        elif not user:
            flash('Login Failed. Check your username', 'danger')
        elif not bcrypt.check_password_hash(user.password, form.password.data):
            flash('Login Failed. Check your password', 'danger')

    return render_template('main/login.html', title='Login', form=form)

@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account/', methods=['GET', 'POST'])
@login_required
def account():
    user = User.query.get_or_404(current_user.id)
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account info updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('main/account.html', title='Account', image_file=image_file, form=form, user=user)


@users.route('/user/<int:user_id>')
def userview(user_id):
    user = User.query.get_or_404(user_id)
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(user_id=user_id).order_by(Post.date_posted.desc()).paginate(per_page=6, page=page)
    return render_template('main/user.html', posts=posts, user=user)


@users.route('/account/img_reset', methods=['POST'])
@login_required
def img_reset():
    user = User.query.get_or_404(current_user.id)

    picture_file = url_for('static', filename='default.jpg')
    current_user.image_file = picture_file
    db.session.commit()
    flash('Image has been reset', 'success')
    return redirect(url_for('users.account'))


@users.route('/reset_request', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Check your email inbox', 'info')
        return redirect(url_for('users.login'))
    return render_template('main/reset_request.html', title='Reset Password', form=form)



@users.route('/reset_request/<token>', methods=['GET', 'POST'])
def change_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid token', 'danger')
        return redirect(url_for('users.reset_request'))
    form = ChangePasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password changed. You can sign in now.', 'success')
        return redirect(url_for('users.login'))
    return render_template('main/change_password.html', title='Reset Password', form=form)
# request token actually, anyway doesn't work properly


@users.route('/user/<int:user_id>/password_change', methods=['GET', 'POST'])
@login_required
def password_change_manually(user_id):
    user = User.query.get_or_404(current_user.id)
    form = ChangePasswordManuallyForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your account info updated', 'success')
        return redirect(url_for('users.account'))
    return render_template('main/change_password_manually.html', title='Change Password', form=form, user=user)

flaskforum/templates/main/about.html
{% extends 'main/zero.html' %}
{% block bud %}
<p>About page</p>
<p><a href="{{ url_for('main.home') }}">Home page</a></p>
{% endblock bud %}

flaskforum/templates/main/account.html
{% extends 'main/zero.html' %}
{% block bud %}
<div class="accountinfo">
    <div class="content-section">
    <img class="accountimage" src="{{ image_file }}"/>
    <div class="media-body">
    <h2 class="account-heading">{{ current_user.username }}</h2>
    <h2 class="account-heading">{{ current_user.email }}</h2>
    </div>
    <div class="logoinfo"></div>
    </div>
    <div>
        <div class="changeinfo"></div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom border-white mb-4">Account Info </legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
             <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}

                    {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br/>
                            {% endfor %}
                    {% endif %}
             </div>
            <div>
                <div><button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#resetModal">
                Reset
                </button>
                </div>
                <div class="form-group">
                    {{ form.submit(class='btn btn-outline-info') }}
                </div>
            </div>
            </form>
            </div>
        </div>
</div>
<div class="modal fade" id="resetModal" tabindex="-1" role="dialog" aria-labelledby="resetModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="resetModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to reset profile image?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('users.img_reset') }}" method="POST">
            <input class="btn btn-primary" type="submit" value="Reset">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock bud %}

flaskforum/templates/main/change_password_manually.html
{% extends 'main/zero.html' %}
{% block bud %}
<div class="reglogforma">
    <form method="POST" action="{{ url_for('users.password_change_manually', user_id= user.id) }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom border-white mb-4">Change Password</legend>
            <div class="form-group">
                {{ form.password.label(class='form-control-label') }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class='form-control-label') }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock bud %}

flaskforum/templates/main/home.html
{% extends 'main/zero.html' %}
{% block bud %}
{% for i in posts.items %}
    <article>
        <div>
            <div class="user_date">
                <a href="{{ url_for('users.userview', user_id=i.author.id) }}"><img src="{{ url_for('static', filename='profile_pics/' + i.author.image_file) }}" class="rounded-circle postimg"></a>
                <a href="{{ url_for('users.userview', user_id=i.author.id) }}">{{ i.author.username }}</a>
                <small class="text-muted">{{ i.date_posted.strftime("%m/%d/%Y, %H:%M") }}</small>
            </div>
            <h3><a href="{{ url_for('posts.post', post_id=i.id) }}">{{ i.title }}</a></h3>
            <p>{{ i.content }}</p>
        </div>
    </article>
{% endfor %}
<div class="page_nums">
    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page %}
            {% if posts.page != page %}
                <a class='btn btn-info' href="{{ url_for('main.home', page=page) }}">{{ page }}</a>
            {% else %}
                <button class="btn btn-secondary">{{ page }}</button>
            {% endif %}
        {% else %}
        {% endif %}
    {% endfor %}
</div>
{% endblock bud%}

flaskforum/templates/main/login.html
{% extends 'main/zero.html' %}
{% block bud %}
<div class="reglogforma">
    <form method="POST" action="{{ url_for('users.login') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom border-white mb-4">Login</legend>
            <div class="form-group">
                {{ form.username.label(class='form-control-label') }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class='form-control-label') }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember }}
                {{ form.remember.label(class='form-check-label') }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
        <small class="text-muted ml-2">
            Forgot Password? <a class="link-primary" href="{{ url_for('users.reset_request') }}">Recover it</a>
        </small>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Don't Have an Account? <a href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
</div>
{% endblock bud %}

flaskforum/templates/main/post.html
{% extends 'main/zero.html' %}
{% block bud %}
    <article class="postview">
        <div>
            <div class="user_date">
                <a href="{{ url_for('users.userview', user_id=post.author.id) }}"><img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="rounded-circle postimg1"></a>
                <h2><a href="{{ url_for('users.userview', user_id=post.author.id) }}">{{ post.author.username }}</a></h2>
                <small class="text-muted">{{ post.date_posted.strftime("%m/%d/%Y, %H:%M") }}</small>
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        {% if post.author == current_user %}
        <div>
        </div>
        <div>
            <a class="btn btn-info btn-sm postupdate" href="{{ url_for('posts.post_update', post_id=post.id) }}">Update Post</a>
            <button type="button" class="btn btn-danger btn-sm postdelete" data-toggle="modal" data-target="#deleteModal">Delete Post</button>
        </div>
        {% endif %}
    </article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              Are you sure you want to delete your post?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.post_delete', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock bud%}

flaskforum/templates/main/register.html
{% extends 'main/zero.html' %}
{% block bud %}
<div class="reglogforma">
    <form method="POST" action="{{ url_for('users.register') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom border-white mb-4">Register</legend>
            <div class="form-group">
                {{ form.username.label(class='form-control-label') }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class='form-control-label') }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class='form-control-label') }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class='form-control-label') }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have an Account? <a href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock bud %}

flaskforum/templates/main/user.html
{% extends 'main/zero.html' %}
{% block bud %}
<div class="accountinfoview">
    <div class="">
    <img class="accountimage" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}"/>
    <div class="media-body">
    <h2 class="account-heading">{{ user.username }}</h2>
    <h2 class="account-heading">{{ user.email }}</h2>
    <small class="text-muted">Posts by {{ user.username }} - {{ posts.total }}</small>
    {% if user == current_user %}
        <a href="{{ url_for('users.account') }}">
            <button class="btn btn-secondary">Edit</button>
        </a>
        <a href="{{ url_for('users.password_change_manually', user_id=user.id) }}">
            <button class="btn btn-secondary">Change Password</button>
        </a>
    {% endif %}
    </div>
    <div>
        {% for i in posts.items %}
            <article class="userarticle">
                <div>
                    <div class="user_date">
                        <small class="text-muted">{{ i.date_posted.strftime("%m/%d/%Y, %H:%M") }}</small>
                    </div>
                    <h3><a href="{{ url_for('posts.post', post_id=i.id) }}">{{ i.title }}</a></h3>
                    <p>{{ i.content }}</p>
                </div>
            </article>
        {% endfor %}
    </div>
        <div class="page_nums_user">
            {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page %}
                    {% if posts.page != page %}
                        <a class='btn btn-info' href="{{ url_for('users.userview', user_id=user.id, page=page) }}">{{ page }}</a>
                    {% else %}
                        <button class="btn btn-secondary">{{ page }}</button>
                    {% endif %}
                {% else %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock bud %}

flaskforum/templates/main/zero.html
<!DOCTYPE html>
<html>
<head>
    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie-edge"><meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no' />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{{ url_for('static', filename='main/css/zero.css')}}">
</head>
<body>
    <header><div class="container">
        <h3 class="navbar-brand mr-4">Flask Blog</h3>
        <a class="navbar-brand mr-4" id="home" href="{{ url_for('main.home') }}">Home</a>
<!--        <a class="navbar-brand mr-4" id="about" href="{{ url_for('main.about') }}">About</a>-->
        {% if current_user.is_authenticated %}
            <a class="navbar-brand mr-4" id="logout" href="{{ url_for('users.logout') }}">Log out</a>
            <a class="navbar-brand mr-4" id="account" href="{{ url_for('users.userview', user_id=current_user.id) }}">{{ current_user.username }}</a>
            <a class="navbar-brand mr-4" id="newpost" href="{{ url_for('posts.new_post') }}">New Post</a>
        {% else %}
            <a class="navbar-brand mr-4" id="login" href="{{ url_for('users.login') }}">Login</a>
            <a class="navbar-brand mr-4" id="reg" href="{{ url_for('users.register') }}">Register</a>
        {% endif %}

        </div>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        {% block bud %}
        {% endblock bud %}
    </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>